CREATE TABLE IF NOT EXISTS TelemetryLogs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT NOT NULL,
  state TEXT NOT NULL,
  batteryLevel REAL NOT NULL,
  lat REAL NOT NULL,
  lng REAL NOT NULL,
  pm25 REAL NOT NULL,
  co2 REAL NOT NULL,
  no2 REAL NOT NULL,
  temperature REAL NOT NULL,
  humidity REAL NOT NULL,
  rssi INTEGER NOT NULL,
  client_timestamp TEXT NOT NULL,
  server_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AlertConfig (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  pm25_threshold REAL NOT NULL DEFAULT 140,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO AlertConfig (id, pm25_threshold) VALUES (1, 140);

CREATE TABLE IF NOT EXISTS Missions (
  id TEXT PRIMARY KEY,
  target_id TEXT NOT NULL,
  target_name TEXT NOT NULL,
  lat REAL NOT NULL,
  lng REAL NOT NULL,
  resource_type TEXT NOT NULL,
  priority TEXT NOT NULL,
  status TEXT NOT NULL,
  report TEXT,
  start_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
